name: HACS Validation

on:
  push:
  pull_request:

jobs:
  validate_hacs:
    name: "HACS Validation"
    runs-on: ubuntu-latest
    steps:
      - uses: "actions/checkout@v2"
      - name: HACS Action
        uses: "hacs/action@main"
        with:
          category: "integration"
  validate_hassfest:
    name: "Hassfest Validation"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v2"
      - uses: home-assistant/actions/hassfest@master